Added tests that expose that the history mechanism works.
It works for both shallow and deep states:

$history is shallow
$history.$history is 1 level deep
$history.$history.$history is 2 levels deep, etc.

Deep history fails if the node in question doesn't have substates,
failing with the following error message:

Error: Cannot read '$history' from state 'history.on.second.A': missing 'initial'