fix action.exec && action.exec()?
should be `typeof action.exec === 'function' && action.exec();`?

because got an error ("TypeError: action.exec is not a function") on `action.exec && action.exec();`